version: "3.9"

services:
  database:
    image: postgres
    container_name: database_list
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=lista
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: lista
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app2
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local